//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Inputs/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Paddles"",
            ""id"": ""949ef690-ddae-4503-899b-b708cf7b97fc"",
            ""actions"": [
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""5bf5eb0d-68a1-4ab7-a5cc-eacf4cd2435d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""0855fba0-8f76-40e6-a8c2-20e2c5f4e263"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Launch"",
                    ""type"": ""Button"",
                    ""id"": ""06aa3c55-0346-4502-b00b-5030e98f0bf6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2880ccd4-84cb-4267-94ce-d87cc8694356"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bfb44ec-aa79-449d-bbd5-4dcb99c3447e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bf52a77-2e63-4a2d-828a-732aaf99dcb9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Launch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Paddles
        m_Paddles = asset.FindActionMap("Paddles", throwIfNotFound: true);
        m_Paddles_Right = m_Paddles.FindAction("Right", throwIfNotFound: true);
        m_Paddles_Left = m_Paddles.FindAction("Left", throwIfNotFound: true);
        m_Paddles_Launch = m_Paddles.FindAction("Launch", throwIfNotFound: true);
    }

    ~@Controls()
    {
        UnityEngine.Debug.Assert(!m_Paddles.enabled, "This will cause a leak and performance issues, Controls.Paddles.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Paddles
    private readonly InputActionMap m_Paddles;
    private List<IPaddlesActions> m_PaddlesActionsCallbackInterfaces = new List<IPaddlesActions>();
    private readonly InputAction m_Paddles_Right;
    private readonly InputAction m_Paddles_Left;
    private readonly InputAction m_Paddles_Launch;
    public struct PaddlesActions
    {
        private @Controls m_Wrapper;
        public PaddlesActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Right => m_Wrapper.m_Paddles_Right;
        public InputAction @Left => m_Wrapper.m_Paddles_Left;
        public InputAction @Launch => m_Wrapper.m_Paddles_Launch;
        public InputActionMap Get() { return m_Wrapper.m_Paddles; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PaddlesActions set) { return set.Get(); }
        public void AddCallbacks(IPaddlesActions instance)
        {
            if (instance == null || m_Wrapper.m_PaddlesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PaddlesActionsCallbackInterfaces.Add(instance);
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Launch.started += instance.OnLaunch;
            @Launch.performed += instance.OnLaunch;
            @Launch.canceled += instance.OnLaunch;
        }

        private void UnregisterCallbacks(IPaddlesActions instance)
        {
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Launch.started -= instance.OnLaunch;
            @Launch.performed -= instance.OnLaunch;
            @Launch.canceled -= instance.OnLaunch;
        }

        public void RemoveCallbacks(IPaddlesActions instance)
        {
            if (m_Wrapper.m_PaddlesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPaddlesActions instance)
        {
            foreach (var item in m_Wrapper.m_PaddlesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PaddlesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PaddlesActions @Paddles => new PaddlesActions(this);
    public interface IPaddlesActions
    {
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnLaunch(InputAction.CallbackContext context);
    }
}
